// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfb1L2L7UKix9R0_w76U9Xfjpe1RN3RmM',
    appId: '1:1003360262878:web:a4a21b1624eb27711c804f',
    messagingSenderId: '1003360262878',
    projectId: 'sheeld-s',
    authDomain: 'sheeld-s.firebaseapp.com',
    storageBucket: 'sheeld-s.appspot.com',
    measurementId: 'G-PNF1554FC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0vnDo5WyqeIKL7GCT_RNc6X6NP_vfrwU',
    appId: '1:1003360262878:android:a924432c932b7a841c804f',
    messagingSenderId: '1003360262878',
    projectId: 'sheeld-s',
    storageBucket: 'sheeld-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaJ1SCltRaJkNYXnrc2-djHJxoZo7fb-s',
    appId: '1:1003360262878:ios:a2245690e70fa6091c804f',
    messagingSenderId: '1003360262878',
    projectId: 'sheeld-s',
    storageBucket: 'sheeld-s.appspot.com',
    iosBundleId: 'net.fluttertutorial.flutterLoginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaJ1SCltRaJkNYXnrc2-djHJxoZo7fb-s',
    appId: '1:1003360262878:ios:a2245690e70fa6091c804f',
    messagingSenderId: '1003360262878',
    projectId: 'sheeld-s',
    storageBucket: 'sheeld-s.appspot.com',
    iosBundleId: 'net.fluttertutorial.flutterLoginUi',
  );
}
